version: '3.9'

services:
  sotatek.hl7.fhir.openapi:
    container_name: Sotatek.HL7.FHIR.OpenAPI
    image: ${DOCKER_REGISTRY-}Sotatekhl7fhiropenapi
    restart: on-failure
    hostname: Sotatek.HL7.FHIR.OpenAPI
    build:
      context: .
      dockerfile: src/Sotatek.Hl7.Fhir.OpenAPI/Dockerfile
    volumes:
      - "./csv-files:/Resources/Files"
